# ---------------------------------------------------------------------------
ifndef SANCUS_SECURITY
    SANCUS_SECURITY=64
endif
ifndef SANCUS_KEY
    ifeq ($(SANCUS_SECURITY), 64)
        SANCUS_KEY=deadbeefcafebabe
    else
        ifeq ($(SANCUS_SECURITY), 128)
            SANCUS_KEY=deadbeefcafebabec0defeeddefec8ed
        else
            $(error SANCUS_KEY not defined (security level $(SANCUS_SECURITY)))
        endif
    endif
endif

# ---------------------------------------------------------------------------
ifndef SANCUS_INSTALL_PREFIX
    SANCUS_INSTALL_PREFIX = /usr/local
endif

# ---------------------------------------------------------------------------
ifndef TI_MSPGCC_INSTALL_PREFIX
    TI_MSPGCC_INSTALL_PREFIX=/opt
endif
ifndef TI_MSPGCC
    TI_MSPGCC = msp430-gcc-6.4.0.32_linux64
endif
TI_MSPGCC_TAR = msp430-gcc-6.4.0.32_linux64.tar.bz2
TI_MSPGCC_URL = http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports

# ---------------------------------------------------------------------------
ifndef SANCUS_CLANG_DEB
    SANCUS_CLANG_DEB=clang-sancus_4.0.0_amd64.deb
endif
SANCUS_CLANG_URL = https://distrinet.cs.kuleuven.be/software/sancus/downloads

# ---------------------------------------------------------------------------
ifeq ($(BUILD_LLVM), 1)
    SANCUS_CLANG = llvm-install
else
    SANCUS_CLANG = clang-deb-install
endif

# ---------------------------------------------------------------------------
SET_ENV = export PATH=$(SANCUS_INSTALL_PREFIX)/bin:$(TI_MSPGCC_INSTALL_PREFIX)/$(TI_MSPGCC)/bin:$$PATH; \
          export LD_LIBRARY_PATH=$(SANCUS_INSTALL_PREFIX)/lib:$$LD_LIBRARY_PATH; 
