# ---------------------------------------------------------------------------
UNAME_M := $(shell uname -m)
OS_VERS := $(shell lsb_release -r 2>/dev/null | awk '{ print $$2 }')
DEBIAN  := $(shell uname -v | grep -c Debian)
UBUNTU  := $(shell uname -v | grep -c Ubuntu)

SUPPORT_PKGS_URL = https://distrinet.cs.kuleuven.be/software/sancus/downloads

# ---------------------------------------------------------------------------
ifndef SANCUS_SECURITY
    SANCUS_SECURITY=64
endif
ifndef SANCUS_KEY
    ifeq ($(SANCUS_SECURITY), 64)
        SANCUS_KEY=deadbeefcafebabe
    else
        ifeq ($(SANCUS_SECURITY), 128)
            SANCUS_KEY=deadbeefcafebabec0defeeddefec8ed
        else
            $(error SANCUS_KEY not defined (security level $(SANCUS_SECURITY)))
        endif
    endif
endif

# ---------------------------------------------------------------------------
ifndef SANCUS_INSTALL_PREFIX
    SANCUS_INSTALL_PREFIX = /usr/local
endif

# ---------------------------------------------------------------------------
SET_ENV = export PATH=$(SANCUS_INSTALL_PREFIX)/bin:$$PATH; \
          export LD_LIBRARY_PATH=$(SANCUS_INSTALL_PREFIX)/lib:$$LD_LIBRARY_PATH; 
